#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Hibla\QueryBuilder\Console\InitCommand;
use Hibla\QueryBuilder\Console\PublishTemplatesCommand;
use Hibla\QueryBuilder\Console\MakeMigrationCommand;
use Hibla\QueryBuilder\Console\MigrateCommand;
use Hibla\QueryBuilder\Console\MigrateRollbackCommand;
use Hibla\QueryBuilder\Console\MigrateResetCommand;
use Hibla\QueryBuilder\Console\MigrateRefreshCommand;
use Hibla\QueryBuilder\Console\MigrateFreshCommand;
use Hibla\QueryBuilder\Console\MigrateStatusCommand;
use Hibla\QueryBuilder\Console\StatusCommand;

$application = new Application('Hibla Query Builder', '1.0.0');

// Register all commands
$application->add(new InitCommand());
$application->add(new PublishTemplatesCommand());
$application->add(new MakeMigrationCommand());
$application->add(new MigrateCommand());
$application->add(new MigrateRollbackCommand());
$application->add(new MigrateResetCommand());
$application->add(new MigrateRefreshCommand());
$application->add(new MigrateFreshCommand());
$application->add(new MigrateStatusCommand());
$application->add(new StatusCommand());

$application->run();